#@baseUrl = https://dev-shanduoduo.sicilyhuang.top
@baseUrl = http://localhost:3000

### Test Update ScrollView - Show
POST {{baseUrl}}/api/ws/update
Content-Type: application/json

{
    "showFlag": true
}

### Test Update ScrollView - Hide
POST {{baseUrl}}/api/ws/update
Content-Type: application/json

{
    "showFlag": false
}

### Test Update ScrollView - Missing showFlag
POST {{baseUrl}}/api/ws/update
Content-Type: application/json

{}

### Test Update ScrollView - Invalid showFlag Type
POST {{baseUrl}}/api/ws/update
Content-Type: application/json

{
    "showFlag": "invalid"
}