### Test Create New WeChat User
POST http://localhost:3000/api/db/wx_users
Content-Type: application/json

{
  "openid": "test_openid_123"
}

### Test Existing WeChat User
POST http://localhost:3000/api/db/wx_users
Content-Type: application/json

{
  "openid": "test_openid_123"
}

### Test Missing OpenID
POST http://localhost:3000/api/db/wx_users
Content-Type: application/json

{}