### Test local OSS images endpoint
GET http://localhost:3000/api/oss/images
Accept: application/json

### Test production health 
GET https://shanduoduo.sicilyhuang.top/api/oss/images
Accept: application/json

### Test production health
# shanduoduo.sicilyhuang.top
GET https://shanduoduo.sicilyhuang.top/api/health

### Test production OSS images endpoint 
GET https://shanduoduo.sicilyhuang.top/api/oss/images
Accept: application/json