### Get all items (Local)
GET http://localhost:3000/api/db/shanduoduo
Accept: application/json

### Get all items (Production)
GET https://shanduoduo.sicilyhuang.top/api/db/shanduoduo
Accept: application/json

### Get item by ID (Local)
GET http://localhost:3000/api/db/items/DR202506281001
Accept: application/json

### Get item by ID (Production)
GET https://shanduoduo.sicilyhuang.top/api/db/items/DR202506281003
Accept: application/json

### Create new item (Local)
POST http://localhost:3000/api/db/items
Content-Type: application/json

{
    "id": "DR202506281002",
    "title": "测试商品",
    "image": "test.jpg",
    "total_units": 12,
    "available_units": 6,
    "location": "测试位置",
    "expire_at": 1698588000,
    "participants": [
        {
            "type": "owner",
            "units": 6,
            "user_name": "测试用户",
            "time": null
        }
    ]
}

### Create new item (Production)
POST https://shanduoduo.sicilyhuang.top/api/db/items
Content-Type: application/json

{
    "id": "DR202506281003",
    "title": "测试商品",
    "image": "test.jpg",
    "total_units": 12,
    "available_units": 6,
    "location": "测试位置",
    "expire_at": 1698588000,
    "participants": [
        {
            "type": "owner",
            "units": 6,
            "user_name": "测试用户",
            "time": null
        }
    ]
}