@baseUrl = https://shanduoduo.sicilyhuang.top/
#@baseUrl = http://localhost:3000

### 获取所有商品 (Local)
GET {{baseUrl}}/api/db/items
Accept: application/json

### 根据ID获取商品详情 (Local)
GET {{baseUrl}}/api/db/items/1
Accept: application/json

### 创建新商品 (Local)
POST {{baseUrl}}/api/db/newItem
Content-Type: application/json

{
  "title": "测试商品",
  "image": "test.jpg",
  "price": 99.99,
  "quantity": 10,
  "unit": "盒",
  "location": "测试位置",
  "expire_at": 1698588000,
  "flavor": [
    {
      "name": "芝士",
      "total": 10
    }
  ]
}

### 获取商品详情 (Local)
GET {{baseUrl}}/api/db/items/8
Accept: application/json


### Add participant with openid
POST {{baseUrl}}/api/db/items/9/participants
Content-Type: application/json

{
  "type": "owner",
  "openid": "test_openid_123",
  "flavor": [
    {
      "name": "芝士",
      "claimed": 2
    }
  ],
  "claim_time": 1698500000
}


### Add participant with openid
POST {{baseUrl}}/api/db/items/4/participants
Content-Type: application/json

{
  "type": "claimed",
  "openid": "test_openid_123",
  "flavor": [
    {
      "name": "芝士",
      "claimed": 2
    }
  ],
  "claim_time": 1698500000
}

### 删除参与者 (Local)
DELETE {{baseUrl}}/api/db/items/1/participants/1
Accept: application/json

### 删除参与者通过 OpenID (Local)
DELETE {{baseUrl}}/api/db/items/1/participants/openid/test_openid_123
Accept: application/json